[from]
chain = "ethereum"
datasource = "rpc"
dapp_type = "uniswap"
http_proxy = "http://localhost:7890" # if you have a bad connection, you can use proxy, so all
start = "2025-1-8"
end = "2025-1-8"

[from.uniswap]
pool_address = "0x88e6A0c2dDD26FEEb64F039a2c41296FcB3f5640"

[from.rpc]
end_point = "http://192.168.0.100:8545"
etherscan_api_key = "Your key at XXXScan"
# If you can not reach etherscan but have a selfhost node, you can set force_no_proxy = true
# this will request etherscan with proxy, but no proxy when request your node.
force_no_proxy = true

[to]
type = "minute" # minute or tick or raw
save_path = "/data/uniswap/ethereum/usdc-eth-005"
skip_existed = true # if file has existed, will skip download. default is false
