from]chain = "ethereum"
datasource = "rpc"
dapp_type = "uniswap"
start = "2025-1-8"
end = "2025-1-8"

[from.uniswap]
pool_address = "0x88e6A0c2dDD26FEEb64F039a2c41296FcB3f5640"


[from.rpc]
end_point = "http://192.168.0.100:8545"
etherscan_api_key = "Your key at XXXScan"
# If you use public node service like alchemy or infura, be sure set thread lower,
# Too frequency requests will get you banned by those service.
thread = 2


[to]
type = "tick"
save_path = "/data/uniswap/ethereum/usdc-eth-005"
skip_existed = true
